### ISSUE TITLE
Wrong Frinkiac urls

### ISSUE THREAD

**Issue by mcg** [morinap/hubot-frinkiac#1]
This stopped worked for me and it ended up being that Frinkiac now does a redirect from www.frinkiac.com/* to just frinkiac.com/*. So the configured URL's probably need to be changed, dropping the "www".

**Comment by morinap** [comment]
Ah, I hadn't noticed the change - thanks! I'll get a new version up today with some updates.

**Comment by morinap** [comment]
Resolved in v1.0.0
